version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_server
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_server
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - mongo

volumes:
  mongo_data:
    driver: local
